package com.security.user.entity.job;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "job_post")
public class JobEntity {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String jobTitle;
    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private String applicationLink;

    @DynamoDBRangeKey(attributeName = "dateOfRelease")
    private Long dateOfRelease;

    @DynamoDBAttribute
    private Long applicationOpenTill;

    @DynamoDBAttribute
    private String experience;
    @DynamoDBAttribute
    private String location;
    @DynamoDBAttribute
    private Boolean isVerified;
}
